# Use the official Python image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Copy your app files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the Streamlit port
EXPOSE 8501

# Run Streamlit app
CMD ["streamlit", "run", "app.py"]
