version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: my_postgres_container
        restart: always
        environment:
            POSTGRES_DB: testdb
            POSTGRES_USER: raghav
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    streamlit:
        build: .
        container_name: my_streamlit_app
        restart: always
        ports:
            - "8501:8501"
        depends_on:
            - postgres

volumes:
    postgres_data: